# Numpy
## Assignment No 3
### 20UCS304

### Bascis of Numpy
Importing package

In [1]:
import numpy as np

* creating numpy array

In [2]:
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


* more than one dimensiona

In [3]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


* using ndmin parameter for setting dimension

In [4]:
a = np.array([1,2,3,4,5,6], ndmin = 2) 
print(a)

[[1 2 3 4 5 6]]


* using dtype parameter for specifing data types

In [5]:
a=np.array([1,2,3,4],dtype=complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

* getting shape of array


In [6]:
arr=np.array([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

* reshaping array

In [7]:
arr=np.array([1,2,3,4,5,6,7,8])
arr.shape=(4,2)
print(arr)
arr=arr.reshape(2,4)
print(arr)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4]
 [5 6 7 8]]


* empty()

creates an uninitialized empty array

In [8]:
x=np.empty([3,3],dtype=int)
x

array([[-553551184,        411,  410788476],
       [ 578617364,  142353020,  192741396],
       [ 545006204,  226295828,  192676212]])

* creating np array from existing list

In [9]:
arr=[1,2,3,4,5,6]
a=np.asarray(arr)
a

array([1, 2, 3, 4, 5, 6])

### Slicing and indexing
* using slice function


In [10]:
a = np.arange(20)
print(a)
s = slice(12,19,2) 
print(a[s])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[12 14 16 18]


* using slicing

In [11]:
a[2:10]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

* items from first column

In [14]:
a[...,0]

array([1, 3, 4])

* items from second column

In [15]:
a[1,...]

array([3, 4, 5])

* items from second column and onwards

In [16]:
a[:,1:]

array([[2, 3],
       [4, 5],
       [5, 6]])

In [17]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
x

array([[1, 2],
       [3, 4],
       [5, 6]])

* specifing specific element

In [18]:
x[[0,1,2], [0,1,1]] 

array([1, 4, 6])

### Matrix operations on array
* Transpose

In [19]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
print("Original :\n",x,"\nTranspose :\n",x.T)

Original :
 [[1 2]
 [3 4]
 [5 6]] 
Transpose :
 [[1 3 5]
 [2 4 6]]


* appending elements

In [20]:
a = np.array([[1,2,3],[4,5,6]]) 
b=np.array([[7,8,9]])
print("a=\n",a,'\nb=\n',b)
print("regular append : ",np.append(a,b))
print("\naxis specified",np.append(a,b,axis=0))


a=
 [[1 2 3]
 [4 5 6]] 
b=
 [[7 8 9]]
regular append :  [1 2 3 4 5 6 7 8 9]

axis specified [[1 2 3]
 [4 5 6]
 [7 8 9]]
